apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb-init-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Fac2Real/monitory-iac.git'
    targetRevision: main
    path: applications/monitory-app/influxdb-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
