apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: {{ .Values.service.name }}
  selector:
    app: kafka-connect
