replicaCount: 1

image:
  repository: confluentinc/cp-kafka
  tag: 7.9.1
  pullPolicy: IfNotPresent

service:
  name: kafka-headless
  type: ClusterIP
  port: 9092

# storage:
#   storageClassName: gp3
#   size: 10Gi

zookeeper:
  host: zookeeper-headless
  port: 2181