apiVersion: v1
kind: Service
metadata:
  name: model-server
spec:
  type: {{ .Values.service.type }}
  selector:
    app: model-server
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.port }}
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    