apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: zookeeper
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      name: client
  selector:
    app: zookeeper
