apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flink
  template:
    metadata:
      labels:
        app: flink
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.containerPortMetrics }}"
        prometheus.io/path: "/"
    spec:
      containers:
        - name: flink
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: webui
              containerPort: {{ .Values.containerPortUI }}
            - name: rpc
              containerPort: {{ .Values.containerPortRPC }}
            - name: metrics
              containerPort: {{ .Values.containerPortMetrics }}
          env:
            - name: AWS_REGION
              value: {{ .Values.awsRegion | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: AWS_SECRET_ACCESS_KEY
