apiVersion: v1
kind: Service
metadata:
  name: flink
  annotations:
    alb.ingress.kubernetes.io/healthcheck-port: "8081"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ui
      port: {{ .Values.containerPortUI }}
      targetPort: {{ .Values.containerPortUI }}
    - name: rpc
      port: {{ .Values.containerPortRPC }}
      targetPort: {{ .Values.containerPortRPC }}
    - name: metrics
      port: {{ .Values.containerPortMetrics }}
      targetPort: {{ .Values.containerPortMetrics }}
  selector:
    app: flink