namespace: default

prometheus:
  image: prom/prometheus:latest
  pvc:
    storageClass: gp3
    size: 20Gi

cloudwatchExporter:
  image: prom/cloudwatch-exporter:latest
  port: 9106

kafkaExporter:
  image: danielqsj/kafka-exporter:latest
  port: 9308
  brokers: kafka-headless.default.svc.cluster.local:9092


influxdbExporter:
  image: prom/influxdb-exporter:latest
  port: 9122
