apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
  template:
    metadata:
      labels:
        app: flink
    spec:
      containers:
        - name: flink
          image: 853660505909.dkr.ecr.ap-northeast-2.amazonaws.com/flink:flink-prod-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
            - containerPort: 6123
          env:
            # - name: AWS_ACCESS_KEY_ID
            #   valueFrom:
            #     configMapKeyRef:
            #       name: flink-config
            #       key: AWS_ACCESS_KEY_ID
            # - name: AWS_SECRET_ACCESS_KEY
            #   valueFrom:
            #     configMapKeyRef:
            #       name: flink-config
            #       key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              value: ap-northeast-2
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: flink-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: flink-secret
                  key: AWS_SECRET_ACCESS_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: flink
spec:
  type: ClusterIP
  ports:
    - name: ui
      port: 8081
      targetPort: 8081
    - name: rpc
      port: 6123
      targetPort: 6123
  selector:
    app: flink
