apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: influxdb-init
          image: influxdb:1.11
          env:
            - name: INFLUXDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: INFLUXDB_USERNAME
            - name: INFLUXDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: INFLUXDB_PASSWORD
            - name: INFLUXDB_DB
              valueFrom:
                configMapKeyRef:
                  name: influxdb-config
                  key: INFLUXDB_DB
          command:
            - sh
            - -c
            - |
              until curl -sf http://influxdb:8086/ping; do
                echo "[wait] InfluxDB not ready"; sleep 3;
              done
              influx -host influxdb -execute "CREATE DATABASE $INFLUXDB_DB"
              if ! influx -host influxdb -execute "SHOW USERS" | grep -q '^$INFLUXDB_USERNAME'; then
                influx -host influxdb -execute "CREATE USER $INFLUXDB_USERNAME WITH PASSWORD '$INFLUXDB_PASSWORD'"
              fi
              if ! influx -host influxdb -execute "SHOW GRANTS FOR $INFLUXDB_USERNAME" | grep -q '$INFLUXDB_DB'; then
                influx -host influxdb -execute "GRANT ALL ON $INFLUXDB_DB TO $INFLUXDB_USERNAME"
              fi
              influx -host influxdb -execute "SHOW GRANTS FOR $INFLUXDB_USERNAME"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-sink
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: influxdb-sink-connector
          image: curlimages/curl:7.85.0
          command:
            - sh
            - -c
            - |
              until curl -sf http://influxdb:8086/ping; do
                echo "[wait] InfluxDB not ready"; sleep 3;
              done
              until curl -sf http://kafka-connect:8083/; do
                echo "[wait] Kafka Connect not ready"; sleep 3;
              done
              response=$(curl -s -w "%{http_code}" -o /tmp/response.json \
                -X POST -H "Content-Type: application/json" \
                --data @/config/influxdb-sink-config.json \
                http://kafka-connect:8083/connectors)
              http_code=$response
              echo "==== Kafka Connect Response ===="
              cat /tmp/response.json
              echo "==== HTTP Status Code: $http_code ===="
              if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
                echo "Connector registered successfully."
              else
                echo "Error registering connector, HTTP status: $http_code"
              fi
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: influxdb-sink-config
