apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  labels:
    app: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox:1.35.0
        command:
          - sh
          - -c
          - |
            until nc -z kafka-headless.default.svc.cluster.local 9092; do
              echo "[init] waiting for Kafka"; sleep 2;
            done

      containers:
      - name: kafka-connect
        image: 853660505909.dkr.ecr.ap-northeast-2.amazonaws.com/eks-test:custom-kafka-connect
        imagePullPolicy: Always
        ports:
          - containerPort: 8083
        env:
          - name: CONNECT_BOOTSTRAP_SERVERS
            value: "kafka-headless.default.svc.cluster.local:9092"
          - name: CONNECT_REST_PORT
            value: "8083"
          - name: CONNECT_REST_ADVERTISED_HOST_NAME
            value: "kafka-connect"
          - name: CONNECT_REST_REQUEST_TIMEOUT_MS
            value: "120000"
          - name: CONNECT_GROUP_ID
            value: "kafka-connect-group"
          - name: CONNECT_CONFIG_STORAGE_TOPIC
            value: "connect-configs"
          - name: CONNECT_OFFSET_STORAGE_TOPIC
            value: "connect-offsets"
          - name: CONNECT_STATUS_STORAGE_TOPIC
            value: "connect-statuses"
          - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
            value: "1"
          - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
            value: "1"
          - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
            value: "1"
          - name: CONNECT_KEY_CONVERTER
            value: "org.apache.kafka.connect.json.JsonConverter"
          - name: CONNECT_VALUE_CONVERTER
            value: "org.apache.kafka.connect.json.JsonConverter"
          - name: CONNECT_INTERNAL_KEY_CONVERTER
            value: "org.apache.kafka.connect.json.JsonConverter"
          - name: CONNECT_INTERNAL_VALUE_CONVERTER
            value: "org.apache.kafka.connect.json.JsonConverter"
          - name: CONNECT_LOG4J_LOGGERS
            value: "org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR"
          - name: CONNECT_PLUGIN_PATH
            value: "/usr/share/java,/usr/share/confluent-hub-components"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
      name: rest
  selector:
    app: kafka-connect
