{{- $pvcName := .Values.pvc.name -}}
{{- $exists := lookup "v1" "PersistentVolumeClaim" .Release.Namespace $pvcName -}}
{{- if not $exists }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcName }}
spec:
  accessModes:
    {{ toYaml .Values.pvc.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClassName }}
{{- end }}
