apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cloudwatch-exporter
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.cloudwatchExporter.port }}
      targetPort: {{ .Values.cloudwatchExporter.port }}
      name: metrics
  selector:
    app: cloudwatch-exporter
