apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-influxdb-exporter
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.influxdbExporter.port }}
      targetPort: {{ .Values.influxdbExporter.port }}
      name: metrics
  selector:
    app: influxdb-exporter
