apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kafka-exporter
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
        - name: kafka-exporter
          image: {{ .Values.kafkaExporter.image }}
          args:
            - "--kafka.server=$(KAFKA_SERVER)"
          ports:
            - containerPort: {{ .Values.kafkaExporter.port }}
          env:
            - name: KAFKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: monitoring-config
                  key: KAFKA_SERVER
